version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:80"

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - jaczetl_website
      - server
