version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.react
    ports:
      - "3000:80"
    volumes:
      - ./client:/app

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - server

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    ports:
      - "5432:5432"
