# Use the official Python image with Python 3.10 as the base image
FROM python:3.10

# Set the working directory in the container
WORKDIR /server

# Copy requirements.txt to the container
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the server files to the container
COPY . .

# Expose the port that your Python server will run on
EXPOSE 5000

# Start the Python server when the container starts
CMD ["python", "app.py"]
